services:
  postgres:
    image: postgres:17
    container_name: ecommerce-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${DB_PORT:-5432}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - backend_net

  backend:
    build:
      context: ./backend/ecommerce-api
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/ecommerce
      DB_USERNAME: ecommerce
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend_net
      - app_net

  frontend:
    build:
      context: ./frontend/ecommerce-web
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app_net

networks:
  backend_net:
  app_net:

volumes:
  postgres_data: