sonar.projectKey=Ecommerce
sonar.projectName=Ecommerce
sonar.sources=backend/ecommerce-api/src/main/java,frontend/ecommerce-web/src
sonar.java.binaries=backend/ecommerce-api/target/classes
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/*.spec.ts